uri: /mgmt/shared/appsvcs/declare
method: POST

tenant_name: "App_Billing_Domain"
application_name: "Customer7_App"
pool_name: "{{application_name}}_Pool"
lb_mode: "least-connections-node"
slow_rptime: 120
snat_value: "self"

common_path: "Common"
http_pf: "/{{common_path}}/http-xff"
tcp_pf: "/{{common_path}}/ssc-tcp-3600"
persist_pf: "/{{common_path}}/ssc-src_addr_1500"
policy_vs: "/{{common_path}}/RDP_Baseline_4-7-16"

client_ssl_pf: "{{application_name}}_CL"
cert_name: "/{{common_path}}/default.crt"
cert_key: "/{{common_path}}/default.key"
cert_chain: "/{{common_path}}/ca-bundle.crt"
ssl_passphrase: "ZjVmNQ=="
passphrase_protected: "eyJhbGciOiJkaXIiLCJlbmMiOiJub25lIn0"

main_vs_name: "{{application_name}}_vs0"
virtual_address: "10.192.98.172"
hasMoreVirtuals: "1"
virtual_servers:
- name: "{{application_name}}_vs1"
  ip: "10.168.98.173"
- name: "{{application_name}}_vs2"
  ip: "10.168.98.174"

pool_members:
- name: "192.168.1.131" 
  port: "80"
  ip: "192.168.1.131"
  status: true
- name: "192.168.1.141"
  port: "80"
  ip: "192.168.1.141"
  status: true
