- name: Push rpms and install onto BIG-IP
  hosts: bigip
  gather_facts: false

  tasks:

# Set Var for curent DO file name
  - name: Retrieve DO Install Version
    find:
      paths: ../files
      patterns: "f5-decl*.rpm"
    register: dorpm
    delegate_to: localhost

# Set Var for curent AS3 file name
  - name: Retrieve AS3 Install Version
    find:
      paths: ../files
      patterns: "f5-appsvcs*.rpm"
    register: as3rpm
    delegate_to: localhost

  - name: Install DO
    bigip_iapplx_package:
      provider: "{{ hostvars[inventory_hostname]['provider']  }}"
      package: "{{ dorpm.files[0].path }}"
    delegate_to: localhost

  - pause:
      seconds: 5

  - name: Install AS3
    bigip_iapplx_package:
      provider: "{{ hostvars[inventory_hostname]['provider']  }}"
      package: "{{ as3rpm.files[0].path }}"
    delegate_to: localhost

  - pause:
      seconds: 5
